// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-patients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_patients_default = defineTool({
  name: "list_patients",
  title: "Listar utentes",
  description: "Lista os utentes da cl\xEDnica do utilizador autenticado. Devolve nome, telefone, email e data de nascimento.",
  inputSchema: {
    search: z.string().trim().optional().describe("Texto opcional para filtrar por nome do utente (cont\xE9m)."),
    limit: z.number().int().min(1).max(100).optional().describe("N\xFAmero m\xE1ximo de utentes a devolver (por omiss\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("pacientes").select("id, nome, telefone, email, data_nascimento").order("nome", { ascending: true }).limit(limit ?? 20);
    if (search) query = query.ilike("nome", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-sessions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_sessions_default = defineTool2({
  name: "list_upcoming_sessions",
  title: "Pr\xF3ximas sess\xF5es",
  description: "Lista as pr\xF3ximas sess\xF5es agendadas na cl\xEDnica do utilizador (a partir de agora), ordenadas por data.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("N\xFAmero m\xE1ximo de sess\xF5es a devolver (por omiss\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const nowIso = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await sb.from("sessoes").select("id, data_hora, status, paciente_id, profissional_id, servico_id").gte("data_hora", nowIso).order("data_hora", { ascending: true }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "efzxtildgdawcplykbdc";
var mcp_default = defineMcp({
  name: "physione-mcp",
  title: "PhysioNE MCP",
  version: "0.1.0",
  instructions: "Ferramentas para a plataforma PhysioNE. Consulta utentes e pr\xF3ximas sess\xF5es da cl\xEDnica do utilizador autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_patients_default, list_upcoming_sessions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
